### ISSUE TITLE
KeyPermanentelyInvalidatedException was added in API 23

### ISSUE THREAD

**Issue by malinajirka** [iamMehedi/Secured-Preference-Store#10]
After upgrading to version 0.4.0, the app doesn't work on Android 4.4
<pre><code>java.lang.NoClassDefFoundError: android.security.keystore.KeyPermanentlyInvalidatedException
                                                                                at devliving.online.securedpreferencestore.EncryptionManager.isRecoverableError(EncryptionManager.java:137)
                                                                                at devliving.online.securedpreferencestore.EncryptionManager.<init>(EncryptionManager.java:127)
                                                                                at devliving.online.securedpreferencestore.SecuredPreferenceStore.<init>(SecuredPreferenceStore.java:42)
                                                                                at devliving.online.securedpreferencestore.SecuredPreferenceStore.getSharedInstance(SecuredPreferenceStore.java:57)</code></pre>

**Comment by malinajirka** [comment]
:) Thank you!
